# fly.toml app configuration file generated for bold-thunder-7022 on 2023-06-23T08:54:41+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-thunder-7022"
primary_region = "syd"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
